export const FETCH_COIN_DATA = "FETCH_COIN_DATA";
export const FETCH_COIN_PRICES = "FETCH_COIN_PRICES";

export const SET_CURRENCY = "SET_CURRENCY";

export const ADD_PORTFOLIO_COIN = "ADD_PORTFOLIO_COIN";
export const EDIT_PORTFOLIO_COIN = "EDIT_PORTFOLIO_COIN";
export const REMOVE_PORTFOLIO_COIN = "REMOVE_PORTFOLIO_COIN";
